# .github/workflows/tests.yml
name: nextflow-tests

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - '**.md'

env:
  NXF_VER: "24.10.9"

jobs:
  utils-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Installs Nextflow and caches its download + plugins.
      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2

      # Speed up repeated runs
      - name: Cache Nextflow
        uses: actions/cache@v4
        with:
          path: |
            ~/.nextflow
            ~/.nf-core
          key: ${{ runner.os }}-nextflow-${{ hashFiles('**/nextflow.config', '**/nextflow.yml', '**/modules/**', '**/lib/**', '**/tests/**') }}
          restore-keys: |
            ${{ runner.os }}-nextflow-

      - name: Run Utils unit tests
        env:
          NXF_VER: "24.10.4"
        run: |
          nextflow -version
          nextflow run tests/test_utils.nf -lib ./lib -ansi-log false
